//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.01
// Generated on Thursday, February 19, 2026 8:03:58 PM

#include <string>

// FRC Includes
#include <networktables/NetworkTableInstance.h>
#include <frc/Timer.h>

#include "Intake.h"
#include "utils/logging/debug/Logger.h"
#include "utils/PeriodicLooper.h"
#include "state/RobotState.h"
#include "utils/DragonPower.h"

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "utils/logging/signals/DragonDataLogger.h"
#include "mechanisms/Intake/OffState.h"
#include "mechanisms/Intake/IntakeState.h"
#include "mechanisms/Intake/ExpelState.h"
#include "mechanisms/Intake/LaunchState.h"
#include "mechanisms/Intake/EmptyHopperState.h"
#include "teleopcontrol/TeleopControl.h"

using ctre::phoenix6::configs::CANdiConfiguration;
using ctre::phoenix6::configs::Slot0Configs;
using ctre::phoenix6::configs::Slot1Configs;
using ctre::phoenix6::configs::TalonFXConfiguration;
using ctre::phoenix6::configs::TalonFXSConfiguration;
using ctre::phoenix6::signals::FeedbackSensorSourceValue;
using ctre::phoenix6::signals::ForwardLimitSourceValue;
using ctre::phoenix6::signals::ForwardLimitTypeValue;
using ctre::phoenix6::signals::GravityTypeValue;
using ctre::phoenix6::signals::InvertedValue;
using ctre::phoenix6::signals::MotorArrangementValue;
using ctre::phoenix6::signals::NeutralModeValue;
using ctre::phoenix6::signals::ReverseLimitSourceValue;
using ctre::phoenix6::signals::ReverseLimitTypeValue;
using ctre::phoenix6::signals::StaticFeedforwardSignValue;

using std::string;
using namespace IntakeStates;

void Intake::CreateAndRegisterStates()
{
	OffState *OffStateInst = new OffState(string("Off"), 0, this, m_activeRobotId);
	AddToStateVector(OffStateInst);

	IntakeState *IntakeStateInst = new IntakeState(string("Intake"), 1, this, m_activeRobotId);
	AddToStateVector(IntakeStateInst);

	ExpelState *ExpelStateInst = new ExpelState(string("Expel"), 2, this, m_activeRobotId);
	AddToStateVector(ExpelStateInst);

	LaunchState *LaunchStateInst = new LaunchState(string("Launch"), 3, this, m_activeRobotId);
	AddToStateVector(LaunchStateInst);

	EmptyHopperState *EmptyHopperStateInst = new EmptyHopperState(string("EmptyHopper"), 4, this, m_activeRobotId);
	AddToStateVector(EmptyHopperStateInst);

	OffStateInst->RegisterTransitionState(IntakeStateInst);
	OffStateInst->RegisterTransitionState(ExpelStateInst);
	OffStateInst->RegisterTransitionState(LaunchStateInst);
	OffStateInst->RegisterTransitionState(EmptyHopperStateInst);
	IntakeStateInst->RegisterTransitionState(OffStateInst);
	IntakeStateInst->RegisterTransitionState(LaunchStateInst);
	IntakeStateInst->RegisterTransitionState(EmptyHopperStateInst);
	ExpelStateInst->RegisterTransitionState(OffStateInst);
	ExpelStateInst->RegisterTransitionState(LaunchStateInst);
	ExpelStateInst->RegisterTransitionState(EmptyHopperStateInst);
	LaunchStateInst->RegisterTransitionState(OffStateInst);
	LaunchStateInst->RegisterTransitionState(IntakeStateInst);
	LaunchStateInst->RegisterTransitionState(ExpelStateInst);
	LaunchStateInst->RegisterTransitionState(EmptyHopperStateInst);
	EmptyHopperStateInst->RegisterTransitionState(OffStateInst);
	EmptyHopperStateInst->RegisterTransitionState(IntakeStateInst);
}

Intake::Intake(RobotIdentifier activeRobotId) : BaseMech(MechanismTypes::MECHANISM_TYPE::INTAKE, std::string("Intake")),
												m_activeRobotId(activeRobotId),
												m_stateMap()
{
	PeriodicLooper::GetInstance()->RegisterAll(this);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::ClimbModeStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::IsLaunching_Bool);
}

std::map<std::string, Intake::STATE_NAMES>
	Intake::stringToSTATE_NAMESEnumMap{
		{"STATE_OFF", Intake::STATE_NAMES::STATE_OFF},
		{"STATE_INTAKE", Intake::STATE_NAMES::STATE_INTAKE},
		{"STATE_EXPEL", Intake::STATE_NAMES::STATE_EXPEL},
		{"STATE_LAUNCH", Intake::STATE_NAMES::STATE_LAUNCH},
		{"STATE_EMPTY_HOPPER", Intake::STATE_NAMES::STATE_EMPTY_HOPPER},
	};

std::map<Intake::STATE_NAMES, std::string>
	Intake::STATE_NAMESEnumToStringMap{
		{Intake::STATE_NAMES::STATE_OFF, "STATE_OFF"},
		{Intake::STATE_NAMES::STATE_INTAKE, "STATE_INTAKE"},
		{Intake::STATE_NAMES::STATE_EXPEL, "STATE_EXPEL"},
		{Intake::STATE_NAMES::STATE_LAUNCH, "STATE_LAUNCH"},
		{Intake::STATE_NAMES::STATE_EMPTY_HOPPER, "STATE_EMPTY_HOPPER"},
	};

void Intake::CreateCompBot302()
{
	m_ntName = "Intake";
	m_intake = new ctre::phoenix6::hardware::TalonFX(16, ctre::phoenix6::CANBus("canivore"));
	m_extender = new ctre::phoenix6::hardware::TalonFXS(11, ctre::phoenix6::CANBus("canivore"));
	m_intakeCANdi = new ctre::phoenix6::hardware::CANdi(11, ctre::phoenix6::CANBus("canivore"));

	m_percentOut = new ControlData(
		ControlModes::CONTROL_TYPE::PERCENT_OUTPUT,		  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_percentOut",									  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDeg = new ControlData(
		ControlModes::CONTROL_TYPE::POSITION_DEGREES,	  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_positionDeg",								  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::VOLTAGE,					 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);

	ReadConstants("Intake.xml", 302);
}

void Intake::InitializeCompBot302()
{
	InitializeTalonFXIntakeCompBot302();
	InitializeTalonFXSExtenderCompBot302();
}
void Intake::InitializeTalonFXIntakeCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_intake->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_intake", "m_intake Status", status.GetName());
}

void Intake::InitializeTalonFXSExtenderCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.OpenLoopRamps.VoltageOpenLoopRampPeriod = units::time::second_t(0);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 11;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Commutation.MotorArrangement = MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 0.56761719;

	configs.Slot0.kI = m_positionDeg->GetI();
	configs.Slot0.kD = m_positionDeg->GetD();
	configs.Slot0.kG = m_positionDeg->GetF();
	configs.Slot0.kS = m_positionDeg->GetS();
	configs.Slot0.kV = m_positionDeg->GetV();
	configs.Slot0.kP = m_positionDeg->GetP();
	configs.Slot0.kA = m_positionDeg->GetA();
	configs.Slot0.GravityType = m_positionDeg->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_positionDeg->GetStaticFeedforwardSign();

	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = ctre::phoenix6::signals::S1CloseStateValue::CloseWhenHigh;
	CANdiConfig.DigitalInputs.S1FloatState = ctre::phoenix6::signals::S1FloatStateValue::PullHigh;

	ctre::phoenix::StatusCode statusMotor = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusMotor = m_extender->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (statusMotor.IsOK())
			break;
	}
	if (!statusMotor.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_extender", "m_extender Status", statusMotor.GetName());

	ctre::phoenix::StatusCode statusCANdi = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusCANdi = m_intakeCANdi->GetConfigurator().Apply(CANdiConfig, units::time::second_t(0.25));
		if (statusCANdi.IsOK())
			break;
	}
	if (!statusCANdi.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_intakeCANdi", "m_intakeCANdi Status", statusCANdi.GetName());
}

void Intake::SetCurrentState(int state, bool run)
{
	StateMgr::SetCurrentState(state, run);
}

void Intake::RunCommonTasks()
{
	// This function is called once per loop before the current state Run()
	ManualControl();
	Cyclic();

	bool isIntakeIn = IsIntakeIn();
	if (m_prevIntakeSwitchState != isIntakeIn)
	{
		m_prevIntakeSwitchState = isIntakeIn;
		NotifyStateUpdate(RobotStateChanges::StateChange::ClimbModeStatus_Bool, isIntakeIn);
	}

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "State", GetCurrentStateName());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "IsIntakeIn", IsIntakeIn());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "IntakePercentOut", m_intakePercentOut.Output.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Intake Position", m_extender->GetPosition().GetValueAsDouble());
}
/// @brief  Set the control constants (e.g. PIDF values).
/// @param [in] ControlData*                                   pid:  the control constants
/// @return void
void Intake::SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier, int slot, ControlData pid)
{
}

/// @brief update the output to the mechanism using the current controller and target value(s)
/// @return void
void Intake::Update()
{
	m_intake->SetControl(*m_intakeActiveTarget);
	m_extender->SetControl(*m_extenderActiveTarget);
}

void Intake::Cyclic()
{
	Update();
}

ControlData *Intake::GetControlData(string name)
{
	if (name.compare("PercentOut") == 0)
		return m_percentOut;
	else if (name.compare("PositionDegree") == 0)
		return m_positionDeg;

	return nullptr;
}
void Intake::NotifyStateUpdate(RobotStateChanges::StateChange change, bool value)
{
	if (change == RobotStateChanges::StateChange::ClimbModeStatus_Bool)
	{
		m_isInClimbMode = value;
	}
	else if (change == RobotStateChanges::StateChange::IsLaunching_Bool)
	{
		m_isLaunching = value;
	}
}
void Intake::ManualControl()
{
	TeleopControl *controller = TeleopControl::GetInstance();
	if (controller != nullptr)
	{
		if (controller->IsButtonPressed(TeleopControlFunctions::EXTENDER_MODIFIER))
		{
			double manualExtenderPercent = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::MANUAL_INTAKE_OUT) - TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::MANUAL_INTAKE_IN);
			UpdateTargetExtenderPercentOut(manualExtenderPercent);
		}
		else
		{
			if (GetCurrentState() != STATE_INTAKE && GetCurrentState() != STATE_EXPEL)
			{
				bool intakeOutPressed = controller->IsButtonPressed(TeleopControlFunctions::FUNCTION::INTAKE_OUT);
				bool intakeInPressed = controller->IsButtonPressed(TeleopControlFunctions::FUNCTION::INTAKE);
				if (intakeOutPressed)
				{
					UpdateTargetExtenderPositionDeg(m_intakeExtendedPositionTarget);
				}
				else if (intakeInPressed)
				{
					UpdateTargetExtenderPositionDeg(m_intakeRetractedPositionTarget);
				}
			}
		}
	}
}
void Intake::DataLog(uint64_t timestamp)
{
	// Control data
	LogDoubleData(timestamp, m_intakePercentOutPath, m_intakePercentOut.Output.value(), m_loggingpercentUnit);

	// Mechanism state
	LogStringData(timestamp, m_intakeStatePath, GetCurrentStateName());
	LogBoolData(timestamp, m_extenderExtendedPath, !IsIntakeIn());
}

std::string Intake::GetCurrentStateName()
{
	STATE_NAMES state = static_cast<STATE_NAMES>(GetCurrentState());
	return (STATE_NAMESEnumToStringMap.find(state) == STATE_NAMESEnumToStringMap.end()) ? "Unknown State" : STATE_NAMESEnumToStringMap.at(state);
}