//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:03 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "frc/Solenoid.h"
#include "utils/logging/signals/DragonDataLogger.h"
#include <frc/DigitalInput.h>
#include <frc/filter/Debouncer.h>

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"
#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

class Intake : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INTAKE,
		STATE_EXPEL,
		STATE_LAUNCH,
		STATE_EMPTY_HOPPER
	};

	Intake(RobotIdentifier activeRobotId);
	Intake() = delete;
	~Intake() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetIntakePercentOut(double percentOut)
	{
		m_intakePercentOut.Output = percentOut;
		m_intakeActiveTarget = &m_intakePercentOut;
	}

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog() override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetIntake() const { return m_intake; }
	frc::Solenoid *GetExtenderLeft() const { return m_extenderLeft; }
	frc::Solenoid *GetExtenderRight() const { return m_extenderRight; }
	bool GetIsIntakeExtendedState() const { return m_isIntakeExtendedIsInverted ? !m_isIntakeExtended->Get() : m_isIntakeExtended->Get(); }
	ControlData *GetPercentOut() const { return m_percentOut; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;
	void SetCurrentState(int state, bool run) override;

	void ManualControl();
	void NotifyStateUpdate(RobotStateChanges::StateChange change, bool value) override;
	bool IsInClimbMode() const { return m_isInClimbMode; }
	bool IsLaunching() const { return m_isLaunching; }
	bool IsIntakeExtended() const { return GetIsIntakeExtendedState(); }

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_intake;
	frc::Solenoid *m_extenderLeft;
	frc::Solenoid *m_extenderRight;
	frc::DigitalInput *m_isIntakeExtended;
	bool m_isIntakeExtendedIsInverted;
	ControlData *m_percentOut;

	void InitializeTalonFXIntakeCompBot302();

	ctre::phoenix6::controls::DutyCycleOut m_intakePercentOut{0.0};
	ctre::phoenix6::controls::ControlRequest *m_intakeActiveTarget;

	bool m_isInClimbMode = false;
	bool m_isLaunching = false;
	bool m_isAllowedToClimb = false;
	// void InitializeLogging();
};