//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.01
// Generated on Thursday, February 19, 2026 8:03:58 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "ctre/phoenix6/CANdi.hpp"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "utils/logging/signals/DragonDataLogger.h"

#include "frc2/command/CommandPtr.h"

#include "mechanisms/base/BaseMech.h"
#include "mechanisms/base/BaseMechSubsystem.h"
#include "mechanisms/configs/MechanismConfigMgr.h"
#include "mechanisms/configs/RobotElementNames.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "state/RobotStateChanges.h"

#include "RobotIdentifier.h"

// Intake command classes - the command-based replacements for the old Intake states.
// Included here so the GetXxxCommand() factories below can be defined inline. These headers
// only forward-declare Intake, so there is no circular include.
#include "mechanisms/Intake/commands/IntakeEmptyHopperCommand.h"
#include "mechanisms/Intake/commands/IntakeExpelCommand.h"
#include "mechanisms/Intake/commands/IntakeIntakeCommand.h"
#include "mechanisms/Intake/commands/IntakeLaunchCommand.h"
#include "mechanisms/Intake/commands/IntakeLoadHopperCommand.h"
#include "mechanisms/Intake/commands/IntakeOffCommand.h"

class Intake : public BaseMechSubsystem, public IRobotStateChangeSubscriber, public DragonDataLogger
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INTAKE,
		STATE_EXPEL,
		STATE_LAUNCH,
		STATE_EMPTY_HOPPER,
		STATE_LOAD_HOPPER,
		STATE_FORCE_INTAKE_AUTON
	};

	Intake(RobotIdentifier activeRobotId);
	Intake() = delete;
	~Intake() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetIntakePercentOut(double percentOut)
	{
		m_intakePercentOut.Output = percentOut;
		m_intakeActiveTarget = &m_intakePercentOut;
	}
	void UpdateTargetExtenderPercentOut(double percentOut)
	{
		m_extenderPercentOut.Output = percentOut;
		m_extenderActiveTarget = &m_extenderPercentOut;
	}
	void UpdateTargetExtenderPositionDeg(units::angle::turn_t position)
	{
		position = std::clamp(position, m_intakeExtendedPositionTarget, m_intakeRetractedPositionTarget);
		m_extenderPositionDeg.Position = position;
		// if (m_cachedExtenderPositionDeg < position)
		// {
		// 	m_extenderActiveTarget = &m_extenderPositionDeg.WithSlot(0);
		// }
		// else
		// {
		// 	m_extenderActiveTarget = &m_extenderPositionDeg.WithSlot(1);
		// }
		m_extenderActiveTarget = &m_extenderPositionDeg.WithSlot(0);
	}

	void Cyclic();
	void Periodic() override;
	void DataLog(uint64_t timestamp) override;

	/// @brief Command factories - the command-based replacements for the old Intake states.
	/// @details Each factory just constructs the matching command class from
	///          mechanisms/Intake/commands/. The command classes own the Initialize()/Execute()/
	///          End()/IsFinished() lifecycle (mirroring the old states' Init()/Run()/Exit()/AtTarget()).
	///          Binding a command with WhileTrue automatically returns the mechanism to its
	///          default (Off) command on release.
	frc2::CommandPtr GetOffCommand() { return IntakeCommands::IntakeOffCommand(this).ToPtr(); }					///< default command (was OffState)
	frc2::CommandPtr GetIntakeCommand() { return IntakeCommands::IntakeIntakeCommand(this).ToPtr(); }			///< was IntakeState / ForceIntakeAutonState
	frc2::CommandPtr GetExpelCommand() { return IntakeCommands::IntakeExpelCommand(this).ToPtr(); }				///< was ExpelState
	frc2::CommandPtr GetLoadHopperCommand() { return IntakeCommands::IntakeLoadHopperCommand(this).ToPtr(); }	///< was LoadHopperState
	frc2::CommandPtr GetLaunchCommand() { return IntakeCommands::IntakeLaunchCommand(this).ToPtr(); }			///< was LaunchState
	frc2::CommandPtr GetEmptyHopperCommand() { return IntakeCommands::IntakeEmptyHopperCommand(this).ToPtr(); } ///< was EmptyHopperState

	/// @brief Map a STATE_NAMES value to the matching command (used by the autonomous bridge).
	frc2::CommandPtr GetCommandForState(STATE_NAMES state)
	{
		switch (state)
		{
		case STATE_INTAKE:
			return GetIntakeCommand();
		case STATE_EXPEL:
			return GetExpelCommand();
		case STATE_LAUNCH:
			return GetLaunchCommand();
		case STATE_EMPTY_HOPPER:
			return GetEmptyHopperCommand();
		case STATE_LOAD_HOPPER:
			return GetLoadHopperCommand();
		case STATE_FORCE_INTAKE_AUTON:
			return GetIntakeCommand();
		case STATE_OFF:
		default:
			return GetOffCommand();
		}
	}

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetIntake() const { return m_intake; }
	ctre::phoenix6::hardware::TalonFXS *GetExtender() const { return m_extender; }
	ctre::phoenix6::hardware::CANdi *GetIntakeCANdi() const { return m_intakeCANdi; }

	ControlData *GetPercentOut() const { return m_percentOut; }
	ControlData *GetPositionDegUp() const { return m_positionDegUp; }
	ControlData *GetPositionDegDown() const { return m_positionDegDown; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;
	static std::map<STATE_NAMES, std::string> STATE_NAMESEnumToStringMap;

	/// @brief Autonomous bridge: schedule the command matching the requested state.
	/// @details Keeps the same signature the old StateMgr exposed so CyclePrimitives and
	///          the auton XML pipeline continue to work unchanged.
	void SetCurrentState(int state, bool run);
	int GetCurrentState() const { return m_currentMode; }
	/// @brief Set the active mode tracker. Used by the Intake command classes in their Initialize().
	void SetCurrentMode(int mode) { m_currentMode = mode; }
	/// @brief First-enable tracking used by IntakeOffCommand to reset the extender exactly once.
	bool HasBeenEnabled() const { return m_hasEnabled; }
	void SetHasBeenEnabled(bool hasEnabled) { m_hasEnabled = hasEnabled; }
	std::string GetCurrentStateName();

	void ManualControl();
	void NotifyStateUpdate(RobotStateChanges::StateChange change, bool value) override;
	bool IsInClimbMode() const { return m_isInClimbMode; }
	bool IsLaunching() const { return m_isLaunching; }
	bool IsIntakeIn() const { return (m_extender->GetReverseLimit(false).GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround); }
	units::angle::turn_t GetCahcedExtenderPositionDegrees() { return m_cachedExtenderPositionDeg; };
	void PublishIntakeMode(bool intaking);

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;
	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_intake;
	ctre::phoenix6::hardware::TalonFXS *m_extender;
	ctre::phoenix6::hardware::CANdi *m_intakeCANdi;

	ControlData *m_percentOut;
	ControlData *m_positionDegUp;
	ControlData *m_positionDegDown;

	void InitializeTalonFXIntakeCompBot302();
	void InitializeTalonFXSExtenderCompBot302();

	ctre::phoenix6::controls::DutyCycleOut m_intakePercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_extenderPercentOut{0.0};
	ctre::phoenix6::controls::PositionVoltage m_extenderPositionDeg{0_tr};
	ctre::phoenix6::controls::ControlRequest *m_intakeActiveTarget = &m_intakePercentOut;
	ctre::phoenix6::controls::ControlRequest *m_extenderActiveTarget = &m_extenderPercentOut;

	bool m_isInClimbMode = false;
	bool m_isLaunching = false;
	bool m_prevIntakeSwitchState = false;

	// Command-based mode tracking + autonomous command handle (replaces StateMgr internals)
	int m_currentMode = STATE_OFF;
	bool m_hasEnabled = false;
	frc2::CommandPtr m_autonCommand;

	units::angle::turn_t m_intakeRetractedPositionTarget{80.0};
	units::angle::turn_t m_intakeExtendedPositionTarget{0.0};
	units::angle::turn_t m_cachedExtenderPositionDeg{0.0};

	static constexpr double m_percentModifier = 0.5;
	static constexpr units::angle::turn_t m_protectExtenderPositionDegDown{-20.0};
	static constexpr units::angle::turn_t m_protectExtenderPositionDegUp{50.0};

	void RefreshCachedMotorData();

	// logging paths
	static constexpr std::string_view m_intakeStatePath = "/Intake/State";
	static constexpr std::string_view m_intakePercentOutPath = "/Intake/TargetPercentOut";
	static constexpr std::string_view m_extenderExtendedPath = "/Intake/Extender/Extended";
	static constexpr std::string_view m_loggingpercentUnit = "Percent";
	static constexpr std::string_view m_loggingExtenderTargetPath = "/Intake/ExtenderTarget";
	static constexpr std::string_view m_loggingExtenderControlRequest = "/Intake/ExtenderControlRequest";
};