//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.01
// Generated on Thursday, February 19, 2026 8:03:58 PM

#pragma once
#include <string>

#include "mechanisms/Intake/Intake.h"
#include "state/State.h"

using namespace std;

namespace IntakeStates
{
	class LaunchState : public State
	{
	public:
		LaunchState() = delete;
		LaunchState(std::string stateName,
					int stateId,
					Intake *mech,
					RobotIdentifier activeRobotId);
		~LaunchState() = default;
		void Init() override;
		void Run() override;
		void Exit() override;
		bool AtTarget() override;
		bool IsTransitionCondition(bool considerGamepadTransitions) override;

	private:
		Intake *m_mechanism;
		void InitCompBot302();
		RobotIdentifier m_RobotId;

		static constexpr double m_intakeTarget = double(0.0);
		// const units::angle::turn_t m_extenderTargetUp = units::angle::turn_t(50);
		// const units::angle::turn_t m_extenderTargetDown = units::angle::turn_t(0);
		static constexpr double m_extenderTargetUp = double(0.25);
		static constexpr double m_extenderTargetDown = double(-0.25);
		double m_currentExtenderTarget = m_extenderTargetUp;

		frc::Timer m_timer;
		static constexpr units::second_t m_bumpDuration = units::second_t(0.375);
	};
}
