//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

class Launcher : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INITIALIZE,
		STATE_IDLE,
		STATE_PREPARE_TO_LAUNCH,
		STATE_LAUNCH,
		STATE_EMPTY_HOPPER,
		STATE_CLIMB
	};

	Launcher(RobotIdentifier activeRobotId);
	Launcher() = delete;
	~Launcher() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetLauncherPercentOut(double percentOut)
	{
		m_launcherPercentOut.Output = percentOut;
		m_launcherActiveTarget = &m_launcherPercentOut;
	}
	void UpdateTargetHoodPercentOut(double percentOut)
	{
		m_hoodPercentOut.Output = percentOut;
		m_hoodActiveTarget = &m_hoodPercentOut;
	}
	void UpdateTargetTransferPercentOut(double percentOut)
	{
		m_transferPercentOut.Output = percentOut;
		m_transferActiveTarget = &m_transferPercentOut;
	}
	void UpdateTargetTurretPercentOut(double percentOut)
	{
		m_turretPercentOut.Output = percentOut;
		m_turretActiveTarget = &m_turretPercentOut;
	}
	void UpdateTargetIndexerPercentOut(double percentOut)
	{
		m_indexerPercentOut.Output = percentOut;
		m_indexerActiveTarget = &m_indexerPercentOut;
	}
	void UpdateTargetHoodPositionDegreesHood(units::angle::turn_t position)
	{
		m_hoodPositionDegreesHood.Position = position;
		m_hoodActiveTarget = &m_hoodPositionDegreesHood.WithSlot(0);
	}
	void UpdateTargetTurretPositionDegreesTurret(units::angle::turn_t position)
	{
		m_turretPositionDegreesTurret.Position = position;
		m_turretActiveTarget = &m_turretPositionDegreesTurret.WithSlot(0);
	}
	void UpdateTargetLauncherVelocityRPS(units::angular_velocity::turns_per_second_t velocity)
	{
		m_launcherVelocityRPS.Velocity = velocity;
		m_launcherActiveTarget = &m_launcherVelocityRPS.WithSlot(0);
	}

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog() override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetLauncher() const { return m_launcher; }
	ctre::phoenix6::hardware::TalonFXS *GetHood() const { return m_hood; }
	ctre::phoenix6::hardware::TalonFX *GetTransfer() const { return m_transfer; }
	ctre::phoenix6::hardware::TalonFXS *GetTurret() const { return m_turret; }
	ctre::phoenix6::hardware::TalonFX *GetIndexer() const { return m_indexer; }
	ControlData *GetPercentOut() const { return m_percentOut; }
	ControlData *GetVelocityRPS() const { return m_velocityRPS; }
	ControlData *GetPositionDegreesHood() const { return m_positionDegreesHood; }
	ControlData *GetPositionDegreesTurret() const { return m_positionDegreesTurret; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_launcher;
	ctre::phoenix6::hardware::TalonFXS *m_hood;
	ctre::phoenix6::hardware::TalonFX *m_transfer;
	ctre::phoenix6::hardware::TalonFXS *m_turret;
	ctre::phoenix6::hardware::TalonFX *m_indexer;
	ControlData *m_percentOut;
	ControlData *m_velocityRPS;
	ControlData *m_positionDegreesHood;
	ControlData *m_positionDegreesTurret;

	void InitializeTalonFXLauncherCompBot302();
	void InitializeTalonFXSHoodCompBot302();
	void InitializeTalonFXTransferCompBot302();
	void InitializeTalonFXSTurretCompBot302();
	void InitializeTalonFXIndexerCompBot302();

	ctre::phoenix6::controls::DutyCycleOut m_launcherPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_hoodPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_transferPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_turretPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_indexerPercentOut{0.0};
	ctre::phoenix6::controls::MotionMagicVoltage m_hoodPositionDegreesHood{units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::MotionMagicVoltage m_turretPositionDegreesTurret{units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_launcherVelocityRPS{units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_launcherActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_hoodActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_transferActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_turretActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_indexerActiveTarget;

	// void InitializeLogging();
};