//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#include <string>

// FRC Includes
#include <frc/Timer.h>
#include <networktables/NetworkTableInstance.h>

#include "Launcher.h"
#include "state/RobotState.h"
#include "utils/DragonPower.h"
#include "utils/PeriodicLooper.h"
#include "utils/logging/debug/Logger.h"

#include "auton/DeadZoneManager.h"
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "mechanisms/Launcher/ClimbState.h"
#include "mechanisms/Launcher/EmptyHopperState.h"
#include "mechanisms/Launcher/IdleState.h"
#include "mechanisms/Launcher/InitializeState.h"
#include "mechanisms/Launcher/LaunchState.h"
#include "mechanisms/Launcher/LauncherTuningState.h"
#include "mechanisms/Launcher/ManualLaunchState.h"
#include "mechanisms/Launcher/OffState.h"
#include "mechanisms/Launcher/PrepareToLaunchState.h"

#include "frc/RobotBase.h"
#include "teleopcontrol/TeleopControl.h"
#include "units/math.h"
#include "utils/InterpolateUtils.h"

using ctre::phoenix6::configs::CANdiConfiguration;
using ctre::phoenix6::configs::Slot0Configs;
using ctre::phoenix6::configs::Slot1Configs;
using ctre::phoenix6::configs::TalonFXConfiguration;
using ctre::phoenix6::configs::TalonFXSConfiguration;
using ctre::phoenix6::signals::FeedbackSensorSourceValue;
using ctre::phoenix6::signals::ForwardLimitSourceValue;
using ctre::phoenix6::signals::ForwardLimitTypeValue;
using ctre::phoenix6::signals::GravityTypeValue;
using ctre::phoenix6::signals::InvertedValue;
using ctre::phoenix6::signals::MotorArrangementValue;
using ctre::phoenix6::signals::NeutralModeValue;
using ctre::phoenix6::signals::ReverseLimitSourceValue;
using ctre::phoenix6::signals::ReverseLimitTypeValue;
using ctre::phoenix6::signals::StaticFeedforwardSignValue;

using std::string;
using namespace LauncherStates;

void Launcher::CreateAndRegisterStates()
{
	OffState *OffStateInst = new OffState(string("Off"), 0, this, m_activeRobotId);
	AddToStateVector(OffStateInst);

	InitializeState *InitializeStateInst = new InitializeState(string("Initialize"), 1, this, m_activeRobotId);
	AddToStateVector(InitializeStateInst);

	IdleState *IdleStateInst = new IdleState(string("Idle"), 2, this, m_activeRobotId);
	AddToStateVector(IdleStateInst);

	PrepareToLaunchState *PrepareToLaunchStateInst = new PrepareToLaunchState(string("PrepareToLaunch"), 3, this, m_activeRobotId);
	AddToStateVector(PrepareToLaunchStateInst);

	LaunchState *LaunchStateInst = new LaunchState(string("Launch"), 4, this, m_activeRobotId);
	AddToStateVector(LaunchStateInst);

	EmptyHopperState *EmptyHopperStateInst = new EmptyHopperState(string("EmptyHopper"), 5, this, m_activeRobotId);
	AddToStateVector(EmptyHopperStateInst);

	ClimbState *ClimbStateInst = new ClimbState(string("Climb"), 6, this, m_activeRobotId);
	AddToStateVector(ClimbStateInst);

	LauncherTuningState *LauncherTuningStateInst = new LauncherTuningState(string("LauncherTuning"), 7, this, m_activeRobotId);
	AddToStateVector(LauncherTuningStateInst);

	ManualLaunchState *ManualLaunchStateInst = new ManualLaunchState(string("ManualLaunch"), 8, this, m_activeRobotId);
	AddToStateVector(ManualLaunchStateInst);

	OffStateInst->RegisterTransitionState(InitializeStateInst);
	InitializeStateInst->RegisterTransitionState(IdleStateInst);
	IdleStateInst->RegisterTransitionState(OffStateInst);
	IdleStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	IdleStateInst->RegisterTransitionState(EmptyHopperStateInst);
	IdleStateInst->RegisterTransitionState(ClimbStateInst);
	IdleStateInst->RegisterTransitionState(LauncherTuningStateInst);
	IdleStateInst->RegisterTransitionState(ManualLaunchStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(OffStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(IdleStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(LaunchStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(EmptyHopperStateInst);
	PrepareToLaunchStateInst->RegisterTransitionState(ClimbStateInst);
	LaunchStateInst->RegisterTransitionState(OffStateInst);
	LaunchStateInst->RegisterTransitionState(IdleStateInst);
	LaunchStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	EmptyHopperStateInst->RegisterTransitionState(OffStateInst);
	EmptyHopperStateInst->RegisterTransitionState(IdleStateInst);
	EmptyHopperStateInst->RegisterTransitionState(ClimbStateInst);
	ClimbStateInst->RegisterTransitionState(OffStateInst);
	ClimbStateInst->RegisterTransitionState(IdleStateInst);
	ClimbStateInst->RegisterTransitionState(PrepareToLaunchStateInst);
	LauncherTuningStateInst->RegisterTransitionState(OffStateInst);
	LauncherTuningStateInst->RegisterTransitionState(LaunchStateInst);
	ManualLaunchStateInst->RegisterTransitionState(OffStateInst);
	ManualLaunchStateInst->RegisterTransitionState(IdleStateInst);
}

Launcher::Launcher(RobotIdentifier activeRobotId) : BaseMech(MechanismTypes::MECHANISM_TYPE::LAUNCHER, std::string("Launcher")),
													m_activeRobotId(activeRobotId),
													m_stateMap(),
													m_chassis(ChassisConfigMgr::GetInstance()->GetSwerveChassis())
{
	PeriodicLooper::GetInstance()->RegisterAll(this);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::AllowedToClimbStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::ClimbModeStatus_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::HubActive_Bool);
	RobotState::GetInstance()->RegisterForStateChanges(this, RobotStateChanges::StateChange::ShiftChangeIn3Seconds_Bool);

	m_targetCalculator = RebuiltTargetCalculator::GetInstance();
}

std::map<std::string, Launcher::STATE_NAMES>
	Launcher::stringToSTATE_NAMESEnumMap{
		{"STATE_OFF", Launcher::STATE_NAMES::STATE_OFF},
		{"STATE_INITIALIZE", Launcher::STATE_NAMES::STATE_INITIALIZE},
		{"STATE_IDLE", Launcher::STATE_NAMES::STATE_IDLE},
		{"STATE_PREPARE_TO_LAUNCH", Launcher::STATE_NAMES::STATE_PREPARE_TO_LAUNCH},
		{"STATE_LAUNCH", Launcher::STATE_NAMES::STATE_LAUNCH},
		{"STATE_EMPTY_HOPPER", Launcher::STATE_NAMES::STATE_EMPTY_HOPPER},
		{"STATE_CLIMB", Launcher::STATE_NAMES::STATE_CLIMB},
		{"STATE_LAUNCHER_TUNING", Launcher::STATE_NAMES::STATE_LAUNCHER_TUNING},
		{"STATE_MANUAL_LAUNCH", Launcher::STATE_NAMES::STATE_MANUAL_LAUNCH}};

std::map<Launcher::STATE_NAMES, std::string>
	Launcher::STATE_NAMESEnumToStringMap{
		{Launcher::STATE_NAMES::STATE_OFF, "STATE_OFF"},
		{Launcher::STATE_NAMES::STATE_INITIALIZE, "STATE_INITIALIZE"},
		{Launcher::STATE_NAMES::STATE_IDLE, "STATE_IDLE"},
		{Launcher::STATE_NAMES::STATE_PREPARE_TO_LAUNCH, "STATE_PREPARE_TO_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_LAUNCH, "STATE_LAUNCH"},
		{Launcher::STATE_NAMES::STATE_EMPTY_HOPPER, "STATE_EMPTY_HOPPER"},
		{Launcher::STATE_NAMES::STATE_CLIMB, "STATE_CLIMB"},
		{Launcher::STATE_NAMES::STATE_LAUNCHER_TUNING, "STATE_LAUNCHER_TUNING"},
		{Launcher::STATE_NAMES::STATE_MANUAL_LAUNCH, "STATE_MANUAL_LAUNCH"}};

void Launcher::CreateCompBot302()
{
	m_ntName = "Launcher";
	m_launcher = new ctre::phoenix6::hardware::TalonFX(8, ctre::phoenix6::CANBus("canivore"));
	m_hood = new ctre::phoenix6::hardware::TalonFXS(7, ctre::phoenix6::CANBus("canivore"));
	m_transfer = new ctre::phoenix6::hardware::TalonFX(4, ctre::phoenix6::CANBus("canivore"));
	m_turret = new ctre::phoenix6::hardware::TalonFXS(6, ctre::phoenix6::CANBus("canivore"));
	m_indexer = new ctre::phoenix6::hardware::TalonFX(5, ctre::phoenix6::CANBus("canivore"));
	m_agitator = new ctre::phoenix6::hardware::TalonFX(18, ctre::phoenix6::CANBus("canivore"));
	m_hoodCANdi = new ctre::phoenix6::hardware::CANdi(7, ctre::phoenix6::CANBus("canivore"));
	m_turretCANdi = new ctre::phoenix6::hardware::CANdi(6, ctre::phoenix6::CANBus("canivore"));

	m_percentOut = new ControlData(
		ControlModes::CONTROL_TYPE::PERCENT_OUTPUT,		  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_percentOut",									  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_velocityRPS = new ControlData(
		ControlModes::CONTROL_TYPE::VELOCITY_REV_PER_SEC, // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_velocityRPS",								  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesHood = new ControlData(
		ControlModes::CONTROL_TYPE::POSITION_DEGREES,	  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_positionDegreesHood",						  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);
	m_positionDegreesTurret = new ControlData(
		ControlModes::CONTROL_TYPE::POSITION_DEGREES,	  // ControlModes::CONTROL_TYPE mode
		ControlModes::CONTROL_RUN_LOCS::MOTOR_CONTROLLER, // ControlModes::CONTROL_RUN_LOCS server
		"m_positionDegreesTurret",						  // std::string indentifier
		0,												  // double proportional
		0,												  // double integral
		0,												  // double derivative
		0,												  // double feedforward
		0,												  // double velocityGain
		0,												  // double accelartionGain
		0,												  // double staticFrictionGain,

		ControlData::FEEDFORWARD_TYPE::DUTY_CYCLE,				 // FEEDFORWARD_TYPE feedforwadType
		0,														 // double integralZone
		0,														 // double maxAcceleration
		0,														 // double cruiseVelocity
		0,														 // double peakValue
		0,														 // double nominalValue
		false,													 // bool enableFOC
		ControlData::GravityTypeValue::Elevator_Static,			 // Gravity type
		ControlData::StaticFeedforwardSignValue::UseVelocitySign // Static feedforward sign
	);

	ReadConstants("Launcher.xml", 302);
}

void Launcher::InitializeCompBot302()
{
	InitializeTalonFXLauncherCompBot302();
	InitializeTalonFXSHoodCompBot302();
	InitializeTalonFXTransferCompBot302();
	InitializeTalonFXSTurretCompBot302();
	InitializeTalonFXIndexerCompBot302();
	InitializeTalonFXAgitatorCompBot302();
}

void Launcher::InitializeTalonFXLauncherCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	configs.Slot0.kI = m_velocityRPS->GetI();
	configs.Slot0.kD = m_velocityRPS->GetD();
	configs.Slot0.kG = m_velocityRPS->GetF();
	configs.Slot0.kS = m_velocityRPS->GetS();
	configs.Slot0.kV = m_velocityRPS->GetV();
	configs.Slot0.kP = m_velocityRPS->GetP();
	configs.Slot0.kA = m_velocityRPS->GetA();
	configs.Slot0.GravityType = m_velocityRPS->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_velocityRPS->GetStaticFeedforwardSign();

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_launcher->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_launcher", "m_launcher Status", status.GetName());
}

void Launcher::InitializeTalonFXSHoodCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);

	// MECH_TODO: Set limit switches
	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 7;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::RemoteCANdiS2;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 7;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	// MECH_TODO: Set Motion Magic params
	configs.MotionMagic.MotionMagicCruiseVelocity = units::angular_velocity::radians_per_second_t(0);
	configs.MotionMagic.MotionMagicAcceleration = units::angular_acceleration::radians_per_second_squared_t(0);
	configs.MotionMagic.MotionMagicJerk = units::angular_jerk::radians_per_second_cubed_t(0);
	configs.Commutation.MotorArrangement = MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 2.293864077669903;

	configs.Slot0.kI = m_positionDegreesHood->GetI();
	configs.Slot0.kD = m_positionDegreesHood->GetD();
	configs.Slot0.kG = m_positionDegreesHood->GetF();
	configs.Slot0.kS = m_positionDegreesHood->GetS();
	configs.Slot0.kV = m_positionDegreesHood->GetV();
	configs.Slot0.kP = m_positionDegreesHood->GetP();
	configs.Slot0.kA = m_positionDegreesHood->GetA();
	configs.Slot0.GravityType = m_positionDegreesHood->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_positionDegreesHood->GetStaticFeedforwardSign();

	ctre::phoenix::StatusCode statusMotor = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusMotor = m_hood->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (statusMotor.IsOK())
			break;
	}
	if (!statusMotor.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_hood", "m_hood Status", statusMotor.GetName());

	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = signals::S1CloseStateValue::CloseWhenHigh;
	CANdiConfig.DigitalInputs.S1FloatState = signals::S1FloatStateValue::PullHigh;

	ctre::phoenix::StatusCode statusCANdi = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusCANdi = m_hoodCANdi->GetConfigurator().Apply(CANdiConfig, units::time::second_t(0.25));
		if (statusCANdi.IsOK())
			break;
	}
	if (!statusCANdi.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_hood", "m_hoodCANdi Status", statusCANdi.GetName());
}

void Launcher::InitializeTalonFXTransferCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 1;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_transfer->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_transfer", "m_transfer Status", status.GetName());
}

void Launcher::InitializeTalonFXSTurretCompBot302()
{
	TalonFXSConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);

	// MECH_TODO: Set limit switches
	configs.HardwareLimitSwitch.ForwardLimitEnable = true;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 6;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::turn_t(267);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::RemoteCANdiS1;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 6;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::turn_t(91);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::RemoteCANdiS2;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	// MECH_TODO: Set Motion Magic params
	configs.MotionMagic.MotionMagicCruiseVelocity = units::angular_velocity::turns_per_second_t(220);
	configs.MotionMagic.MotionMagicAcceleration = units::angular_acceleration::turns_per_second_squared_t(400);
	configs.MotionMagic.MotionMagicJerk = units::angular_jerk::radians_per_second_cubed_t(0);
	configs.Commutation.MotorArrangement = MotorArrangementValue::Minion_JST;

	configs.ExternalFeedback.ExternalFeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.ExternalFeedback.SensorToMechanismRatio = 2.341053459459459 / 4;

	configs.Slot0.kI = m_positionDegreesTurret->GetI();
	configs.Slot0.kD = m_positionDegreesTurret->GetD();
	configs.Slot0.kG = m_positionDegreesTurret->GetF();
	configs.Slot0.kS = m_positionDegreesTurret->GetS();
	configs.Slot0.kV = m_positionDegreesTurret->GetV();
	configs.Slot0.kP = m_positionDegreesTurret->GetP();
	configs.Slot0.kA = m_positionDegreesTurret->GetA();
	configs.Slot0.GravityType = m_positionDegreesTurret->GetGravityType();
	configs.Slot0.StaticFeedforwardSign = m_positionDegreesTurret->GetStaticFeedforwardSign();

	ctre::phoenix::StatusCode statusMotor = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusMotor = m_turret->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (statusMotor.IsOK())
			break;
	}
	if (!statusMotor.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turret", "m_turret Status", statusMotor.GetName());

	CANdiConfiguration CANdiConfig{};

	CANdiConfig.DigitalInputs.S1CloseState = signals::S1CloseStateValue::CloseWhenHigh;
	CANdiConfig.DigitalInputs.S1FloatState = signals::S1FloatStateValue::PullHigh;
	CANdiConfig.DigitalInputs.S2CloseState = signals::S2CloseStateValue::CloseWhenHigh;
	CANdiConfig.DigitalInputs.S2FloatState = signals::S2FloatStateValue::PullHigh;

	ctre::phoenix::StatusCode statusCANdi = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		statusCANdi = m_turretCANdi->GetConfigurator().Apply(CANdiConfig, units::time::second_t(0.25));
		if (statusCANdi.IsOK())
			break;
	}
	if (!statusCANdi.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_turret", "m_turretCANdi Status", statusCANdi.GetName());
}

void Launcher::InitializeTalonFXIndexerCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.25);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::CounterClockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Coast;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 3;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_indexer->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_indexer", "m_indexer Status", status.GetName());
}

void Launcher::InitializeTalonFXAgitatorCompBot302()
{
	TalonFXConfiguration configs{};
	configs.CurrentLimits.StatorCurrentLimit = units::current::ampere_t(100);
	configs.CurrentLimits.StatorCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLimit = units::current::ampere_t(70);
	configs.CurrentLimits.SupplyCurrentLimitEnable = true;
	configs.CurrentLimits.SupplyCurrentLowerLimit = units::current::ampere_t(35);
	configs.CurrentLimits.SupplyCurrentLowerTime = units::time::second_t(0);

	configs.Voltage.PeakForwardVoltage = units::voltage::volt_t(11.0);
	configs.Voltage.PeakReverseVoltage = units::voltage::volt_t(-11.0);
	configs.ClosedLoopRamps.TorqueClosedLoopRampPeriod = units::time::second_t(0.05);

	configs.HardwareLimitSwitch.ForwardLimitEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ForwardLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ForwardLimitSource = ForwardLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ForwardLimitType = ForwardLimitTypeValue::NormallyOpen;

	configs.HardwareLimitSwitch.ReverseLimitEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitRemoteSensorID = 0;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = false;
	configs.HardwareLimitSwitch.ReverseLimitAutosetPositionValue = units::angle::degree_t(0);
	configs.HardwareLimitSwitch.ReverseLimitSource = ReverseLimitSourceValue::LimitSwitchPin;
	configs.HardwareLimitSwitch.ReverseLimitType = ReverseLimitTypeValue::NormallyOpen;

	configs.MotorOutput.Inverted = InvertedValue::Clockwise_Positive;
	configs.MotorOutput.NeutralMode = NeutralModeValue::Brake;
	configs.MotorOutput.PeakForwardDutyCycle = 1;
	configs.MotorOutput.PeakReverseDutyCycle = -1;
	configs.MotorOutput.DutyCycleNeutralDeadband = 0;

	configs.Feedback.FeedbackSensorSource = FeedbackSensorSourceValue::RotorSensor;
	configs.Feedback.SensorToMechanismRatio = 3;

	ctre::phoenix::StatusCode status = ctre::phoenix::StatusCode::StatusCodeNotInitialized;
	for (int i = 0; i < 5; ++i)
	{
		status = m_agitator->GetConfigurator().Apply(configs, units::time::second_t(0.25));
		if (status.IsOK())
			break;
	}
	if (!status.IsOK())
		Logger::GetLogger()->LogData(LOGGER_LEVEL::ERROR, "m_agitator", "m_agitator Status", status.GetName());
}

void Launcher::SetCurrentState(int state, bool run)
{
	StateMgr::SetCurrentState(state, run);
}

void Launcher::RefreshCachedMotorData()
{
	m_cachedLauncherVelocity = m_launcher->GetVelocity().GetValue();
	m_cachedHoodPosition = m_hood->GetPosition().GetValue();
	m_cachedTurretPosition = m_turret->GetPosition().GetValue();
}

void Launcher::RunCommonTasks()
{
	// Refresh all motor data once at the start of the loop to avoid multiple CAN bus queries
	RefreshCachedMotorData();

	if (frc::DriverStation::IsDisabled())
	{
		InitilaizeLauncher();
	}

	// This function is called once per loop before the current state Run()
	Cyclic();
	SetLauncherProtect();

	// Update Launcher Targets/Field
	m_targetCalculator->UpdateTargetOffset();
	CalculateTargets();
	UpdateLauncherTargets();

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Current State", GetCurrentStateName());
}

/// @brief  Set the control constants (e.g. PIDF values).
/// @param [in] ControlData*                                   pid:  the control constants
/// @return void
void Launcher::SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier, int slot, ControlData pid)
{
}

/// @brief update the output to the mechanism using the current controller and target value(s)
/// @return void
void Launcher::Update()
{
	m_launcher->SetControl(*m_launcherActiveTarget);
	m_hood->SetControl(*m_hoodActiveTarget);
	m_transfer->SetControl(*m_transferActiveTarget);
	m_turret->SetControl(*m_turretActiveTarget);
	m_indexer->SetControl(*m_indexerActiveTarget);
	m_agitator->SetControl(*m_agitatorActiveTarget);
}

void Launcher::Cyclic()
{
	Update();
}

ControlData *Launcher::GetControlData(string name)
{
	if (name.compare("PercentOut") == 0)
		return m_percentOut;
	if (name.compare("VelocityRPS") == 0)
		return m_velocityRPS;
	if (name.compare("PositionDegreesHood") == 0)
		return m_positionDegreesHood;
	if (name.compare("PositionDegreesTurret") == 0)
		return m_positionDegreesTurret;

	return nullptr;
}

void Launcher::PublishLaunchMode(bool launching)
{
	RobotState::GetInstance()->PublishStateChange(RobotStateChanges::StateChange::IsLaunching_Bool, launching);
}

void Launcher::NotifyStateUpdate(RobotStateChanges::StateChange statechange, bool value)
{
	if (statechange == RobotStateChanges::StateChange::ClimbModeStatus_Bool)
	{
		m_isClimbMode = value;
	}
	else if (statechange == RobotStateChanges::StateChange::AllowedToClimbStatus_Bool)
	{
		m_isAllowedToClimb = value;
	}
	else if (statechange == RobotStateChanges::StateChange::HubActive_Bool)
	{
		m_isHubActive = value;
	}
	else if (statechange == RobotStateChanges::StateChange::ShiftChangeIn3Seconds_Bool)
	{
		m_shiftChangeIn3Seconds = value;
	}
}

bool Launcher::IsLauncherAtTarget()
{

	if (frc::RobotBase::IsSimulation() && !(GetCurrentState() == STATE_NAMES::STATE_LAUNCHER_TUNING))
	{
		return true;
	}
	// Launcher Speed error, Hood Angle error, Turret angle error are within a threshold, and if we are in launch zone. Also check chassis speed.
	units::angle::degree_t hoodError = m_cachedHoodPosition - m_targetHoodAngle;
	units::angular_velocity::revolutions_per_minute_t launcherSpeedError = m_cachedLauncherVelocity - m_targetLauncherAngularVelocity;
	bool inLaunchzone = IsInLaunchZone();
	auto chassisSpeeds = m_chassis != nullptr ? m_chassis->GetState().Speeds : frc::ChassisSpeeds();

	auto Speed = units::math::sqrt(units::math::abs(chassisSpeeds.vx * chassisSpeeds.vx) + units::math::abs(chassisSpeeds.vy * chassisSpeeds.vy));

	return ((units::math::abs(hoodError) < m_hoodAngleThreshold) &&
			IsTurretAtTarget() &&
			(units::math::abs(launcherSpeedError) < m_launcherVelocityThreshold) &&
			(inLaunchzone) &&
			(Speed < m_chassisSpeedThreshold));
}

bool Launcher::IsInLaunchZone() const
{
	if (!DeadZoneManager::GetInstance()->IsInDeadZone())
	{
		return !(AllianceZoneManager::GetInstance()->IsInAllianceZone() && !(m_isHubActive || m_shiftChangeIn3Seconds));
	}
	return false;
}

void Launcher::CalculateTargets()
{

	if (units::math::abs(m_targetTurretAngle - m_targetCalculator->GetLauncherTarget(m_lookaheadTime, m_cachedTurretPosition)) > 0.1_tr)
	{
		m_targetTurretAngle = m_targetCalculator->GetLauncherTarget(m_lookaheadTime, m_cachedTurretPosition);
	}
	units::length::inch_t distanceToTarget = m_targetCalculator->CalculateDistanceToTarget(m_lookaheadTime);

	if (AllianceZoneManager::GetInstance()->IsInAllianceZone())
	{
		m_targetHoodAngle = InterpolateUtils::linearInterpolate(m_scoringDistanceArray, m_scoringHoodAngleArray, distanceToTarget);
		m_targetLauncherAngularVelocity = InterpolateUtils::linearInterpolate(m_scoringDistanceArray, m_scoringLauncherVelocityArray, distanceToTarget);
	}
	else
	{
		m_targetHoodAngle = InterpolateUtils::linearInterpolate(m_passingDistanceArray, m_passingHoodAngleArray, units::length::foot_t(distanceToTarget));
		m_targetLauncherAngularVelocity = InterpolateUtils::linearInterpolate(m_passingDistanceArray, m_passingLauncherVelocityArray, units::length::foot_t(distanceToTarget));
	}

	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Distance To Target", distanceToTarget.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Hood Angle Target", m_targetHoodAngle.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Launcher Turret Angle", m_cachedTurretPosition.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Launcher Turret Target", m_targetTurretAngle.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Launcher Speed Target", m_targetLauncherAngularVelocity.value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Launcher Speed RPM", units::angular_velocity::revolutions_per_minute_t(m_cachedLauncherVelocity).value());
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, m_ntName, "Hood Angle", m_cachedHoodPosition.value());
}

void Launcher::UpdateLauncherTargets()
{
	int currentState = GetCurrentState();

	if (currentState == STATE_NAMES::STATE_OFF || currentState == STATE_NAMES::STATE_INITIALIZE || currentState == STATE_NAMES::STATE_CLIMB || currentState == STATE_NAMES::STATE_MANUAL_LAUNCH || m_tuningLauncher)
	{
		return;
	}

	UpdateTargetHoodPositionDegreesHood(m_targetHoodAngle);
	UpdateTargetTurretPositionDegreesTurret(m_targetTurretAngle);
	UpdateTargetLauncherVelocityRPS(m_targetLauncherAngularVelocity);
}

void Launcher::InitilaizeLauncher()
{
	if (((m_turret->GetReverseLimit().GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround ||
		  m_turret->GetForwardLimit().GetValue() == ctre::phoenix6::signals::ForwardLimitValue::ClosedToGround) &&
		 (m_hood->GetReverseLimit().GetValue() == ctre::phoenix6::signals::ReverseLimitValue::ClosedToGround)) ||
		frc::RobotBase::IsSimulation())
	{
		m_launcherInitialized = true;
	}
}

void Launcher::SetLauncherProtect()
{
	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::LAUNCHER_OFF))
	{
		if (m_launcherOffButtonReleased)
		{
			m_launcherProtectedMode = !m_launcherProtectedMode;
		}
		m_launcherOffButtonReleased = false;
	}
	else
	{
		m_launcherOffButtonReleased = true;
	}
}

std::string Launcher::GetCurrentStateName()
{
	STATE_NAMES state = static_cast<STATE_NAMES>(GetCurrentState());
	return (STATE_NAMESEnumToStringMap.find(state) == STATE_NAMESEnumToStringMap.end()) ? "Unknown State" : STATE_NAMESEnumToStringMap.at(state);
}

bool Launcher::IsTurretAtTarget()
{
	units::angle::degree_t turretError = m_cachedTurretPosition - m_targetTurretAngle;

	return ((units::math::abs(turretError) < m_turretAngleThreshold));
}