//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

// Includes after generation
#include "utils/RebuiltTargetCalculator.h"

class Launcher : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INITIALIZE,
		STATE_IDLE,
		STATE_PREPARE_TO_LAUNCH,
		STATE_LAUNCH,
		STATE_EMPTY_HOPPER,
		STATE_CLIMB,
		STATE_LAUNCHER_TUNING
	};

	Launcher(RobotIdentifier activeRobotId);
	Launcher() = delete;
	~Launcher() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetLauncherPercentOut(double percentOut)
	{
		m_launcherPercentOut.Output = percentOut;
		m_launcherActiveTarget = &m_launcherPercentOut;
	}
	void UpdateTargetHoodPercentOut(double percentOut)
	{
		m_hoodPercentOut.Output = percentOut;
		m_hoodActiveTarget = &m_hoodPercentOut;
	}
	void UpdateTargetTransferPercentOut(double percentOut)
	{
		m_transferPercentOut.Output = percentOut;
		m_transferActiveTarget = &m_transferPercentOut;
	}
	void UpdateTargetTurretPercentOut(double percentOut)
	{
		m_turretPercentOut.Output = percentOut;
		m_turretActiveTarget = &m_turretPercentOut;
	}
	void UpdateTargetIndexerPercentOut(double percentOut)
	{
		m_indexerPercentOut.Output = percentOut;
		m_indexerActiveTarget = &m_indexerPercentOut;
	}
	void UpdateTargetHoodPositionDegreesHood(units::angle::turn_t position)
	{
		m_hoodPositionDegreesHood.Position = position;
		m_hoodActiveTarget = &m_hoodPositionDegreesHood.WithSlot(0);
	}
	void UpdateTargetTurretPositionDegreesTurret(units::angle::turn_t position)
	{
		m_turretPositionDegreesTurret.Position = position;
		m_turretActiveTarget = &m_turretPositionDegreesTurret.WithSlot(0);
	}
	void UpdateTargetLauncherVelocityRPS(units::angular_velocity::turns_per_second_t velocity)
	{
		m_launcherVelocityRPS.Velocity = velocity;
		m_launcherActiveTarget = &m_launcherVelocityRPS.WithSlot(0);
	}

	void UpdateTargetAgitatorPercentOut(double percentOut)
	{
		m_agitatorPercentOut.Output = percentOut;
		m_agitatorActiveTarget = &m_agitatorPercentOut;
	}

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog() override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetLauncher() const { return m_launcher; }
	ctre::phoenix6::hardware::TalonFXS *GetHood() const { return m_hood; }
	ctre::phoenix6::hardware::TalonFX *GetTransfer() const { return m_transfer; }
	ctre::phoenix6::hardware::TalonFXS *GetTurret() const { return m_turret; }
	ctre::phoenix6::hardware::TalonFX *GetIndexer() const { return m_indexer; }
	ctre::phoenix6::hardware::TalonFX *GetAgitator() const { return m_agitator; }

	ControlData *GetPercentOut() const { return m_percentOut; }
	ControlData *GetVelocityRPS() const { return m_velocityRPS; }
	ControlData *GetPositionDegreesHood() const { return m_positionDegreesHood; }
	ControlData *GetPositionDegreesTurret() const { return m_positionDegreesTurret; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;
	bool IsLauncherInProtectedMode() const { return m_launcherProtectedMode; }
	void PublishLaunchMode(bool launching);
	void NotifyStateUpdate(RobotStateChanges::StateChange statechange, bool value) override;
	bool IsInClimbMode() const { return m_isClimbMode; }
	bool IsAllowedToClimb() const { return m_isAllowedToClimb; }
	bool IsLauncherAtTarget();
	bool IsInLaunchZone() const;
	bool IsLauncherInitialized() const { return m_launcherInitialized; }
	void SetLauncherInitialized(bool initialized) { m_launcherInitialized = initialized; }
	bool IsTuningLauncherMode() const { return m_tuningLauncher; }
	void UpdateLauncherTargets();

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_launcher;
	ctre::phoenix6::hardware::TalonFXS *m_hood;
	ctre::phoenix6::hardware::TalonFX *m_transfer;
	ctre::phoenix6::hardware::TalonFXS *m_turret;
	ctre::phoenix6::hardware::TalonFX *m_indexer;
	ctre::phoenix6::hardware::TalonFX *m_agitator;

	ControlData *m_percentOut;
	ControlData *m_velocityRPS;
	ControlData *m_positionDegreesHood;
	ControlData *m_positionDegreesTurret;

	void InitializeTalonFXLauncherCompBot302();
	void InitializeTalonFXSHoodCompBot302();
	void InitializeTalonFXTransferCompBot302();
	void InitializeTalonFXSTurretCompBot302();
	void InitializeTalonFXIndexerCompBot302();
	void InitializeTalonFXAgitatorCompBot302();

	ctre::phoenix6::controls::DutyCycleOut m_launcherPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_hoodPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_transferPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_turretPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_indexerPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_agitatorPercentOut{0.0};
	ctre::phoenix6::controls::MotionMagicVoltage m_hoodPositionDegreesHood{units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::MotionMagicVoltage m_turretPositionDegreesTurret{units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_launcherVelocityRPS{units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_launcherActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_hoodActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_transferActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_turretActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_indexerActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_agitatorActiveTarget;

	bool m_launcherProtectedMode = false;
	bool m_launcherOffButtonReleased = true;
	bool m_isClimbMode = false;
	bool m_isAllowedToClimb = false;

	units::time::second_t m_lookaheadTime = 0.5_s;

	units::angle::degree_t m_targetTurretAngle = 0.0_deg;
	units::angular_velocity::revolutions_per_minute_t m_targetLauncherAngularVelocity = 0.0_rpm;
	units::angle::degree_t m_targetHoodAngle = 0.0_deg;

	units::angle::degree_t m_turretAngleThreshold = 5.0_deg;
	units::angular_velocity::revolutions_per_minute_t m_launcherVelocityThreshold = 25.0_rpm;
	units::angle::degree_t m_hoodAngleThreshold = 3.0_deg;
	units::velocity::meters_per_second_t m_chassisSpeedThreshold = 1.0_mps;

	RebuiltTargetCalculator *m_targetCalculator;

	void CalculateTargets();

	bool m_launcherInitialized = false;
	bool m_tuningLauncher = false;

	// TODO MECH tune and change values in these arrays
	std::array<units::length::inch_t, 10> m_scoringDistanceArray = {20.0_in, 40.0_in, 60.0_in, 80.0_in, 100.0_in, 120.0_in, 140.0_in, 160.0_in, 180.0_in, 200.0_in};
	std::array<units::angle::degree_t, 10> m_scoringHoodAngleArray = {0.0_deg, 5.0_deg, 10.0_deg, 15.0_deg, 20.0_deg, 25.0_deg, 30.0_deg, 35.0_deg, 40.0_deg, 45.0_deg};
	std::array<units::angular_velocity::revolutions_per_minute_t, 10> m_scoringLauncherVelocityArray = {500.0_rpm, 600.0_rpm, 700.0_rpm, 800.0_rpm, 900.0_rpm, 1000.0_rpm, 1100.0_rpm, 1200.0_rpm, 1300.0_rpm, 1400.0_rpm};

	std::array<units::length::foot_t, 7> m_passingDistanceArray = {10.0_ft, 15.0_ft, 20.0_ft, 25.0_ft, 30.0_ft, 35.0_ft, 40.0_ft};
	std::array<units::angle::degree_t, 7> m_passingHoodAngleArray = {0.0_deg, 5.0_deg, 10.0_deg, 15.0_deg, 20.0_deg, 25.0_deg, 30.0_deg};
	std::array<units::angular_velocity::revolutions_per_minute_t, 7> m_passingLauncherVelocityArray = {500.0_rpm, 600.0_rpm, 700.0_rpm, 800.0_rpm, 900.0_rpm, 1000.0_rpm, 1100.0_rpm};

	// void InitializeLogging();
};