//====================================================================================================================================================
// Copyright 2026 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.26.00.00
// Generated on Thursday, January 22, 2026 11:43:04 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configuration.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

class Launcher : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INITIALIZE,
		STATE_IDLE,
		STATE_PREPARE_TO_LAUNCH,
		STATE_LAUNCH,
		STATE_EMPTY_HOPPER,
		STATE_CLIMB
	};

	Launcher(RobotIdentifier activeRobotId);
	Launcher() = delete;
	~Launcher() = default;

	void CreateCompBot302();
	void InitializeCompBot302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetLauncherPercentOut(double percentOut)
	{
		m_LauncherPercentOut.Output = percentOut;
		m_LauncherActiveTarget = &m_LauncherPercentOut;
	}
	void UpdateTargetHoodPercentOut(double percentOut)
	{
		m_HoodPercentOut.Output = percentOut;
		m_HoodActiveTarget = &m_HoodPercentOut;
	}
	void UpdateTargetTransferPercentOut(double percentOut)
	{
		m_TransferPercentOut.Output = percentOut;
		m_TransferActiveTarget = &m_TransferPercentOut;
	}
	void UpdateTargetTurretPercentOut(double percentOut)
	{
		m_TurretPercentOut.Output = percentOut;
		m_TurretActiveTarget = &m_TurretPercentOut;
	}
	void UpdateTargetIndexerPercentOut(double percentOut)
	{
		m_IndexerPercentOut.Output = percentOut;
		m_IndexerActiveTarget = &m_IndexerPercentOut;
	}
	void UpdateTargetHoodPositionDegreesHood(units::angle::turn_t position)
	{
		m_HoodPositionDegreesHood.Position = position;
		m_HoodActiveTarget = &m_HoodPositionDegreesHood.WithSlot(0);
	}
	void UpdateTargetTurretPositionDegreesTurret(units::angle::turn_t position)
	{
		m_TurretPositionDegreesTurret.Position = position;
		m_TurretActiveTarget = &m_TurretPositionDegreesTurret.WithSlot(0);
	}
	void UpdateTargetLauncherVelocityRPS(units::angular_velocity::turns_per_second_t velocity)
	{
		m_LauncherVelocityRPS.Velocity = velocity;
		m_LauncherActiveTarget = &m_LauncherVelocityRPS.WithSlot(0);
	}

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	// void DataLog() override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetLauncher() const { return m_Launcher; }
	ctre::phoenix6::hardware::TalonFXS *GetHood() const { return m_Hood; }
	ctre::phoenix6::hardware::TalonFX *GetTransfer() const { return m_Transfer; }
	ctre::phoenix6::hardware::TalonFXS *GetTurret() const { return m_Turret; }
	ctre::phoenix6::hardware::TalonFX *GetIndexer() const { return m_Indexer; }
	ControlData *GetPercentOut() const { return m_PercentOut; }
	ControlData *GetVelocityRPS() const { return m_VelocityRPS; }
	ControlData *GetPositionDegreesHood() const { return m_PositionDegreesHood; }
	ControlData *GetPositionDegreesTurret() const { return m_PositionDegreesTurret; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_Launcher;
	ctre::phoenix6::hardware::TalonFXS *m_Hood;
	ctre::phoenix6::hardware::TalonFX *m_Transfer;
	ctre::phoenix6::hardware::TalonFXS *m_Turret;
	ctre::phoenix6::hardware::TalonFX *m_Indexer;
	ControlData *m_PercentOut;
	ControlData *m_VelocityRPS;
	ControlData *m_PositionDegreesHood;
	ControlData *m_PositionDegreesTurret;

	void InitializeTalonFXLauncherCompBot302();
	void InitializeTalonFXSHoodCompBot302();
	void InitializeTalonFXTransferCompBot302();
	void InitializeTalonFXSTurretCompBot302();
	void InitializeTalonFXIndexerCompBot302();

	ctre::phoenix6::controls::DutyCycleOut m_LauncherPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_HoodPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_TransferPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_TurretPercentOut{0.0};
	ctre::phoenix6::controls::DutyCycleOut m_IndexerPercentOut{0.0};
	ctre::phoenix6::controls::MotionMagicVoltage m_HoodPositionDegreesHood{units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::MotionMagicVoltage m_TurretPositionDegreesTurret{units::angle::degree_t(0.0)};
	ctre::phoenix6::controls::VelocityVoltage m_LauncherVelocityRPS{units::angular_velocity::turns_per_second_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_LauncherActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_HoodActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_TransferActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_TurretActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_IndexerActiveTarget;

	// void InitializeLogging();
};